### ISSUE TITLE
Framebuffer header tag semantics unclear

### ISSUE THREAD

**Issue by davmac314** [stivale/stivale#11]
I've just been experimenting with Limine (via UEFI) and was surprised when it refused to boot a kernel which didn't include the Framebuffer header tag.

The text currently says:
> This tag asks the stivale2-compliant bootloader to initialise a graphical framebuffer video mode. Omitting this tag will make the bootloader default to a CGA-compatible text mode, if supported.

What it doesn't say is what will happen if a CGA-compatible text mode is _not_ supported. It seems that this causes Limine, when booted via EFI, to refuse to boot the OS.

So, oddly, a kernel which doesn't care whether it boots in text or graphics (framebuffer) mode, has to supply a framebuffer header tag; it has to supply this tag even if it won't use the framebuffer at all, otherwise it won't be bootable via an EFI-based bootloader which doesn't know how to set text mode.

Currently my options are:
1. include the framebuffer header tag, then I will always get booted in graphics mode even if I don't care (unless the bootloader doesn't support the tag), but at least it will be possible to boot via UEFI or when text mode isn't otherwise available. I have no way to specify a preference for text mode, or to indicate that I have no preference between text/framebuffer modes.
2. don't include the framebuffer header tag, and it won't be possible to boot via UEFI :(

I think the text should at least clarify the situation, but I'd also be personally inclined to change current semantics so that the framebuffer tag isn't required in this situation. If backwards compatibility is considered necessary, it'd be possible to add a flag bit (or bits) in the main header to indicate that "CGA-compatible text mode is not required" (i.e it's ok to boot in framebuffer mode if text mode isn't available)  and/or "this kernel doesn't care which type of video mode is set" (i.e. the mode shouldn't be changed from whatever it "naturally" is at boot time, even if the framebuffer header tag *is* present).

**Comment by mintsuki** [comment]
Hello.
You raise a compelling issue here. It is definitely something that has been overlooked and should be sorted out.

Would an additional "no video" tag which, if present, overrides the framebuffer tag and makes the bootloader not set any specific video mode in particular, and boot anywhere, suffice?

**Comment by davmac314** [comment]
That would definitely be an improvement!

One thought: a kernel might not _require_ any particular video mode, but it still might be able to make use of either framebuffer (or even a CGA-compatible text screen) _if_ they are available. So even if the "no video" tag is set, the framebuffer info tag should still be passed to the OS, if there is a framebuffer available.

**Comment by mintsuki** [comment]
The above commit should suffice to address all the concerns in this issue. It will be implemented in the next Limine release.

**Comment by davmac314** [comment]
Nice, thanks!
