### ISSUE TITLE
stivale2 structs have byte alignment - intentional?

### ISSUE THREAD

**Issue by davmac314** [stivale/stivale#12]
All the stivale2 structs are declared as `__attribute__((packed))`, eg:

```
struct stivale2_hdr_tag {
    uint64_t identifier;
    uint64_t next;
} __attribute__((packed));
```

However, this gives them byte alignment, which seems unlikely to be actually wanted, and it could easily cause problems.

One way to resolve would be to add a specified alignment, eg:

```
struct stivale2_hdr_tag {
    uint64_t identifier;
    uint64_t next;
} __attribute__((packed, aligned(_Alignof(uint64_t))));
```

However, I'm really wondering if "packed" should be specified at all:
- on common architectures it is unnecessary (eg above example will not have padding bytes inserted even without "packed" attribute on x86, ARM or any other architecture that stivale is likely to be used on)
- if on an architecture with unusual alignment requirements, "packed" attribute may subvert those requirements; I'm not sure there's a good rationale for doing that, especially as it can cause problems.

**Comment by mintsuki** [comment]
Byte alignment is intended. What `__attribute__((packed))` here is supposed to mean is that the structs are laid out in memory as-is, the same as the are defined. No padding should exist between members even if they happen to be misaligned.

Now, I am perfectly aware that in most (if not all) of these cases the attribute is useless as the members are already properly aligned, and that is also intended.

Correct me here if I am wrong, but on architectures that do not support misaligned pointer dereferences, the compiler is smart enough to break the access down into multiple, aligned accesses, as to not cause trouble to the underlying ISA. What could be problematic is taking a pointer to a misaligned member (which is the reason why GCC issues a warning should you attempt to do so).

**Comment by davmac314** [comment]
> Byte alignment is intended. What __attribute__((packed)) here is supposed to mean is that the structs are laid out in memory as-is, the same as the are defined. No padding should exist between members even if they happen to be misaligned.

Ok, but it also affects the alignment of the struct.

What is the rationale for packing the structure? - are you concerned about wasting memory due to padding? Do you want to ensure the layout is exactly the same on different architectures (if so, why)? Or is it something else?

Similarly, what is the rationale for allowing the structures to have byte alignment? Is this flexibility beneficial for implementations in some way that I'm not seeing?

> Correct me here if I am wrong, but on architectures that do not support misaligned pointer dereferences, the compiler is smart enough to break the access down into multiple, aligned accesses

I believe that is correct, but there is a cost in code size and performance of course.

**Comment by mintsuki** [comment]
I will go ahead and remove the packed attribute where possible, you are right, it is kind of ugly.

**Comment by mintsuki** [comment]
It will also improve compatibility for compilers that do not support the attribute.

**Comment by mintsuki** [comment]
Oops I closed accidentally.
