### ISSUE TITLE
Other Executable Formats

### ISSUE THREAD

**Issue by circutrider21** [stivale/stivale#9]
I was wondering if there is any stivale compatible loaders that have support for other executable format aside from elf, like PE or MachO. It would be quite neat!

**Comment by StaticSaga** [comment]
The Stivale specs only support ELF for now, as it's the simplest and most ubiquitous format (so Limine, Sabaton and TomatBoot can only load ELF stivale kernels).
> In order to have a stivale2 compliant kernel, one must have a kernel executable in the elf64 or elf32 format and have a .stivale2hdr section (described below). Other executable formats are not supported.

ELF is pretty much universal nowadays, and the only modern compiler that doesn't target it is MSVC. If you really want to use Visual Studio for developing stivale-compliant kernels, you can still use VS's native Clang integration.

**Comment by circutrider21** [comment]
I was trying to create a darwin style kernel, so MachO is a must. I just asked here because I have used stivale bootloaders in the past and really like how simple the spec is.

**Comment by StaticSaga** [comment]
You can still make an ELF kernel which uses Mach-O to load userspace executables (for example you can still load a.out or COFF executables on ELF linux).
If you **really** want a Mach-O kernel, you can add support to Limine for the format: while harder than using ELF, it's still considerably easier than writing your own full bootloader.

**Comment by 0xqoob** [comment]
Idk we'll work on it now ig

**Comment by AtieP** [comment]
> Idk we'll work on it now ig

Yeah qob work on it to get a prize :meme:

**Comment by circutrider21** [comment]
Ok guys, thanks for the help. I'll start working on a pull request for MachO limine support!
